version: "2"
services:

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  recipe-crud:
    image: "kuharskimojster/recepie-crud:1.0.0-SNAPSHOT-13.1"
    #build: ../recipe-crud
    environment:
      -SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
      -SPRING_DATASOURE_USERNAME: "postgres"
      -SPRING_DATASOURCE_PASSWORD: "postgres"
      -KAFKA_ADDRESS: "kafka:9092"
      -LOGGING_FILE_PATH: "logging/application.log"
      -SPRING_BOOT_ADMIN_CLIENT_URL: "http://admin:8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
      - admin

  recipe-filter:
    image: "kuharskimojster/filter:1.0.0-SNAPSHOT-9.1"
    #build: ../filter
    environment:
      -SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
      -SPRING_DATASOURE_USERNAME: "postgres"
      -SPRING_DATASOURCE_PASSWORD: "postgres"
      -LOGGING_FILE_PATH: "logging/application.log"
      -SPRING_BOOT_ADMIN_CLIENT_URL: "http://admin:8080"
    depends_on:
      - db
      - admin
    ports:
      - "9080:9080"

  subscriptions:
    image: "kuharskimojster/subscriptions:1.0.0-SNAPSHOT-2.1"
    #build: ../subscriptions
    environment:
      -SPRING_DATA_NEO4J_URI: "bolt://neo:7687"
      -SPRING_DATA_NEO4J_USERNAME: "neo4j"
      -SPRING_DATA_NEO4J_PASSWORD: "pass"
      -KAFKA_RATINGS_TOPIC: "ratings"
      -KAFKA_COMMENTS_TOPIC: "comments"
      -KAFKA_ADDRESS: "kafka:9092"
      -LOGGING_FILE_PATH: "logging/application.log"
      -SPRING_BOOT_ADMIN_CLIENT_URL: "http://admin:8080"
    depends_on:
      - kafka
      - admin
    ports:
      - "7080:8080"

  ratings:
    image: "kuharskimojster/ratings:1.0.0-SNAPSHOT-3.1"
    #build: ../ratings
    environment:
      -SPRING_DATA_NEO4J_URI: "bolt://neo:7687"
      -SPRING_DATA_NEO4J_USERNAME: "neo4j"
      -SPRING_DATA_NEO4J_PASSWORD: "pass"
      -KAFKA_TOPIC: "subscriptions"
      -KAFKA_ADDRESS: "kafka:9092"
      -LOGGING_FILE_PATH: "logging/application.log"
      -SPRING_BOOT_ADMIN_CLIENT_URL: "http://admin:8080"
    depends_on:
      - kafka
    ports:
      - "6080:8080"

  recommendations:
    #image: "recommendations"
    build: ../recommendations
    environment:
      -SPRING_DATA_NEO4J_URI: "bolt://neo:7687"
      -SPRING_DATA_NEO4J_USERNAME: "neo4j"
      -SPRING_DATA_NEO4J_PASSWORD: "pass"
      -LOGGING_FILE_PATH: "logging/application.log"
      -SPRING_BOOT_ADMIN_CLIENT_URL: "http://admin:8080"
    depends_on:
      - neo
      - admin
    ports:
      - "5080:9080"
  
  admin:
    build: ../admin-server
    ports:
      - "4080:8080"

  neo:
    # this image is AGPLv3 licensed: https://www.graphfoundation.org/projects/ongdb/
    build: neo4j/
    #image: "kuharskimojster/neo:1.0.0-SNAPSHOT-1"
    restart: always
    hostname: neo
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_AUTH=neo4j/pass
    depends_on:
      - kafka
      - zk


  zk:
    # this image is Apache 2.0 licensed: https://hub.docker.com/r/confluentinc/cp-zookeeper
    hostname: zk
    restart: always
    image: confluentinc/cp-zookeeper:5.3.0
    ports:
      - "2181:2181"
    environment:
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    # this image is Apache 2.0 licensed: https://hub.docker.com/r/confluentinc/cp-kafka
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zk:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  ksql:
  # the base of this image is Apache 2.0 licensed: https://hub.docker.com/r/confluentinc/cp-kafka-connect-base/
    image: confluentinc/cp-ksql-server
    restart: always
    ports:
      - 8088:8088
    environment:
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_LISTENERS: http://0.0.0.0:8088
